Popover
innowacja2022-dapp-TTPSC/TTPSC-App pull request #42
Opened 2023-01-20 21:15 UTC by matiduda

There shouldn't be any conflicts with [https://github.com/innowacja2022-dapp-TTPSC/TTPSC-Rewards-DApp/pull/41](previous PR)

2023-01-20 22:05 UTC, MrDell1 requested changes
Try not to use ```<Spacer> , <Center>``` , minW, minH. Try to Flex and padding insted

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/ManagePage.tsx
> +    <>
Remove this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/ManagePage.tsx
> +          >
Just use Flex here we don't need Grid it's simple component

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/ManagePage.tsx
> +                    <b>Transactions</b>
Don't use <b>, use fontWeights. https://chakra-ui.com/docs/styled-system/theme#typography

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/panels/AwardsPanel.tsx
> +        </Box>
You can delete this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/panels/RequestsPanel.tsx
> +        </Box>
You can delete this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/panels/TransactionsPanel.tsx
> +        </Box>
You can delete this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/panels/UsersPanel.tsx
> +        </Box>
You can delete this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +        <>
You can delete this

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +}
Remove this we want to dispaly wallet Address

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                        {daytimeBasedMessage()}
change it to walletAddress

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/ManagePage.tsx
> +                  padding="20px"
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/Admin/ManagePage.tsx
> +            >
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                            <Box w="40px" h="40px" borderRadius="50px" bgColor="black">
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                            <Text fontWeight='semibold' fontSize="15px" paddingLeft="10px" maxWidth="150px" style={{
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                                    fontSize="13px"
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                                    marginLeft="5px"
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                        <Text fontWeight='bold' fontSize="20px" paddingLeft="10px" w='100%'>0,00</Text>
Use chakra spacing. https://chakra-ui.com/docs/styled-system/theme#spacing

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/DisconnectWallet/DisconnectWallet.tsx
>  };
Change name from DionnectWallet, to Menu.

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +import { CloseIcon, CopyIcon } from '@chakra-ui/icons';
Move this folder to folder with Modal

ContentWraper
-Menu
--PopoverMenu

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +    disconnectFunction: Function;
use ```() => void``` insted of Function

2023-01-20 22:05 UTC, MrDell1 commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +    walletAddress: String;
use ```string``` not ``String```

2023-01-20 22:36 UTC, matiduda commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                        {daytimeBasedMessage()}
why have the exact information doubled next to each other?

2023-01-20 22:39 UTC, matiduda commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +                        <Text fontWeight='bold' fontSize="20px" paddingLeft="10px" w='100%'>0,00</Text>
I think its better to stick with pixel since we used it from the beginning

2023-01-20 22:44 UTC, matiduda commented on frontend/src/routes/ContentWraper/TopBar/PopoverMenu/PopoverMenu.tsx
> +}
same as below

2023-01-21 11:42 UTC, MrDell1 approved these changes

2023-01-21 11:43 UTC, merged